### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [cgnov/Parstagram#1]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:
- User can sign up to create a new account using Parse authentication
- The current signed in user is persisted across app restarts
- User can take a photo, add a caption, and post it to "Instagram"
- User can pull to refresh the last 20 posts submitted to "Instagram"

Also the following stretch user stories listed are not clearly shown:
- After the user submits a new post, show an indeterminate progress bar while the post is being uploaded to Parse

Can you make an update and resubmit?

**Comment by cgnov** [comment]
Sign up and progress bar fixed, gif added, and project resubmitted. Thank you for pointing it out!

**Comment by cgnov** [comment]
Sign up and progress bar fixed, gif added, and project resubmitted. Thank you for pointing it out!

**Comment by codepathreview** [comment]
Thank you for letting us know!

Nice work, Camila. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
